id = "efa-theme"
name = "Efa Theme"
version = "1.0.0"
schema_version = 1
authors = ["Yefimov Valentyn <valentine.efimov@gmail.com>"]
description = "A JetBrains-inspired dark theme for Zed with balanced contrast and refined syntax colors."
repository = "https://github.com/valyefimov/zed-theme-efa-dark"
